# Generated by Django 2.2.24 on 2021-09-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subjects',
            new_name='Subject',
        ),
    ]
