# Generated by Django 2.2.24 on 2021-10-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='option_num',
        ),
    ]
