# Generated by Django 2.2.24 on 2021-10-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_problem_option_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='content',
            field=models.TextField(default='次のうちから正しいものを１つ選びなさい', verbose_name='問題文'),
        ),
    ]
