# Generated by Django 2.2.24 on 2021-09-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choice_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.Problem'),
            preserve_default=False,
        ),
    ]
