# Generated by Django 2.2.24 on 2021-10-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_problem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct',
            field=models.IntegerField(default=0, verbose_name='正解番号'),
        ),
    ]
