# Generated by Django 2.2.24 on 2021-10-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_problem_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct',
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_choice',
            field=models.IntegerField(default=1, verbose_name='正解の選択肢'),
        ),
    ]
