# Generated by Django 2.2.24 on 2021-09-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210911_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
    ]
